### ISSUE TITLE
Ek Uygulama İsteği 

### ISSUE THREAD

**Issue by Mehmet-I** [symbuzzer/MIUI-Debloater-Magisk-Modules#2]
Merhaba Ali Bey,

Çalışmanızdan dolayı teşekkürlerimi iletiyorum. Gerçekten oldukça beğendim.
Adhost listenizi de kullanan birisi olarak o liste için de ayrıca teşekkür ediyorum.

Debloat listesinde Mi Tarayıcı(browser) uygulamasını göremedim. Eğer mümkünse bunu da müstakil olarak ekleyebilir misiniz? Ayrıca müstakil modülleri birlikte kullanmanın bir sakıncası var mıdır merak ediyorum. 

İyi çalışmalar dilerim.

**Comment by Mehmet-I** [comment]
> Merhaba Ali Bey,
> 
> Çalışmanızdan dolayı teşekkürlerimi iletiyorum. Gerçekten oldukça beğendim.
> Adhost listenizi de kullanan birisi olarak o liste için de ayrıca teşekkür ediyorum.
> 
> Debloat listesinde Mi Tarayıcı(browser) uygulamasını göremedim. Eğer mümkünse bunu da müstakil olarak ekleyebilir misiniz? Ayrıca müstakil modülleri birlikte kullanmanın bir sakıncası var mıdır merak ediyorum. 
> 
> İyi çalışmalar dilerim.

(Bu arada redmi note 9 pro kullanıyorum. Mi videoyu da kaldırmama rağmen mi dosya yöneticisi ile video açtığımda aynısı açılıyor maalesef. Dosya yöneticisinden pek rahatsız değildim.)

**Comment by symbuzzer** [comment]
> > Merhaba Ali Bey,
> > Çalışmanızdan dolayı teşekkürlerimi iletiyorum. Gerçekten oldukça beğendim.
> > Adhost listenizi de kullanan birisi olarak o liste için de ayrıca teşekkür ediyorum.
> > Debloat listesinde Mi Tarayıcı(browser) uygulamasını göremedim. Eğer mümkünse bunu da müstakil olarak ekleyebilir misiniz? Ayrıca müstakil modülleri birlikte kullanmanın bir sakıncası var mıdır merak ediyorum.
> > İyi çalışmalar dilerim.
> 
> (Bu arada redmi note 9 pro kullanıyorum. Mi videoyu da kaldırmama rağmen mi dosya yöneticisi ile video açtığımda aynısı açılıyor maalesef. Dosya yöneticisinden pek rahatsız değildim.)

Merhaba, tabi ki Mi Tarayıcıyı ayrı bir modül olarak ekleyebilirim. Mi video'daki sorunu da çözebiliriz. Ama her ikisi için de yardımınız gerekli. Bu uygulamaların dosya konumlarını bana ulaştırmanız gerekiyor. Bunları bulabilir misiniz? Eğer bana bunları iletebilirseniz her iki modülü de kolaylıkla hazırlayabilirim. 

Müstakil modülleri birlikte kullanabilirsiniz, zaten amaç o :)

**Comment by Mehmet-I** [comment]
Tabii konumları gönderebilirim. Bu konumlar kök içerisinde mi? Öyleyse bana örnek bir uygulamanın konumunu gönderir misiniz? Mi Music konumu gibi

Ayrı ayrı kurdum modları ve çalıştı ama gene de bir sorayım dedim :) açıklamada da öyle yazıyordu zaten ya :)))

**Comment by symbuzzer** [comment]
> Tabii konumları gönderebilirim. Bu konumlar kök içerisinde mi? Öyleyse bana örnek bir uygulamanın konumunu gönderir misiniz? Mi Music konumu gibi
> 
> Ayrı ayrı kurdum modları ve çalıştı ama gene de bir sorayım dedim :) açıklamada da öyle yazıyordu zaten ya :)))

system/app system/priv-app product/app product/priv-app vendor/app vendor/priv-app buralara bakmanız lazım

**Comment by Mehmet-I** [comment]
> > Tabii konumları gönderebilirim. Bu konumlar kök içerisinde mi? Öyleyse bana örnek bir uygulamanın konumunu gönderir misiniz? Mi Music konumu gibi
> > 
> > Ayrı ayrı kurdum modları ve çalıştı ama gene de bir sorayım dedim :) açıklamada da öyle yazıyordu zaten ya :)))
> 
> system/app system/priv-app product/app product/priv-app vendor/app vendor/priv-app buralara bakmanız lazım

![IMG_20230519_102410.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/32801de9-d620-4487-b02a-e99fca4ec58b)

![IMG_20230519_102511.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/560fe0ac-6b9e-43b6-97d4-3afcb3700752)

![IMG_20230519_102255.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/1881bc9b-a7b4-45a8-a6bf-dbb88304c255)

![IMG_20230519_102334.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/450186cb-b324-4e71-b266-4ccb0e4b0a1f)

**Comment by symbuzzer** [comment]
Dosya yöneticisi ce Mivideo magisk modulünün çalışıyor olması lazım?

Diğerlerini hazırlıyorum...

**Comment by Mehmet-I** [comment]
> Dosya yöneticisi ce Mivideo magisk modulünün çalışıyor olması lazım?
> 
> Diğerlerini hazırlıyorum...

Onu kullanırken açtığım videolar mi videoyu açıyor. O sebeple attım. Aslında silmek istemiyorum iyi bir alternatif bulana kadar. Varsa tavsiyeniz bakabilirim :)

**Comment by symbuzzer** [comment]
> > Dosya yöneticisi ce Mivideo magisk modulünün çalışıyor olması lazım?
> > Diğerlerini hazırlıyorum...
> 
> Onu kullanırken açtığım videolar mi videoyu açıyor. O sebeple attım. Aslında silmek istemiyorum iyi bir alternatif bulana kadar. Varsa tavsiyeniz bakabilirim :)

Yeni modülleri ekledim. Güle güle kullanın. 
Dosya yöneticisi olarak ben de miui'ninkini kullanıyordum.

**Comment by Mehmet-I** [comment]
> > > Dosya yöneticisi ce Mivideo magisk modulünün çalışıyor olması lazım?
> > > Diğerlerini hazırlıyorum...
> > 
> > Onu kullanırken açtığım videolar mi videoyu açıyor. O sebeple attım. Aslında silmek istemiyorum iyi bir alternatif bulana kadar. Varsa tavsiyeniz bakabilirim :)
> 
> Yeni modülleri ekledim. Güle güle kullanın. 
> Dosya yöneticisi olarak ben de miui'ninkini kullanıyordum.

Modüller maalesef çalışmadı. ![Screenshot_2023-05-19-11-39-02-263_com.mi.globalbrowser.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/7851edea-6534-4b73-96d1-a9e1ac8fb7aa)

![Screenshot_2023-05-19-11-39-22-869_dtr.jp.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/755a06ce-0bca-4e8e-b312-5c058f5a247c)

Eksik konum attım sanırım değil mi?

**Comment by symbuzzer** [comment]
> Eksik konum attım sanırım değil mi?

Hayır, güncellemeleri kaldırmadın. Uygulamaların üzerine basılı tut ve kaldır de

**Comment by Mehmet-I** [comment]
> > > > > Dosya yöneticisi ce Mivideo magisk modulünün çalışıyor olması lazım?
> > > > > Diğerlerini hazırlıyorum...
> > > > 
> > > > 
> > > > Onu kullanırken açtığım videolar mi videoyu açıyor. O sebeple attım. Aslında silmek istemiyorum iyi bir alternatif bulana kadar. Varsa tavsiyeniz bakabilirim :)
> > > 
> > > 
> > > Yeni modülleri ekledim. Güle güle kullanın.
> > > Dosya yöneticisi olarak ben de miui'ninkini kullanıyordum.
> > 
> > Modüller maalesef çalışmadı. ![Screenshot_2023-05-19-11-39-02-263_com.mi.globalbrowser.jpg](https://user-images.githubusercontent.com/63732211/239484705-7851edea-6534-4b73-96d1-a9e1ac8fb7aa.jpg)
> > 
> > ![Screenshot_2023-05-19-11-39-22-869_dtr.jp.jpg](https://user-images.githubusercontent.com/63732211/239484706-755a06ce-0bca-4e8e-b312-5c058f5a247c.jpg)
> > 
> > Eksik konum attım sanırım değil mi?
> 
> Hayır, güncellemeleri kaldırmadın. Uygulamaların üzerine basılı tut ve kaldır de

Tümünü kaldırıp reboot attım sonra yükleyip tekrar yeniden başlattım. Tarayıcı ve oyun merkezi duruyor maalesef.

![Screenshot_2023-05-19-12-02-29-622_com.miui.home.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/840f71b8-5a82-47e0-b69e-db0feb86b237)

**Comment by symbuzzer** [comment]
@Mehmet-I  tekrar kodlara bakıp döneceğim

**Comment by symbuzzer** [comment]
@Mehmet-I kodlarda bir sıkıntı yok. klasörler yanlış olabilir mi?

**Comment by Mehmet-I** [comment]
> @Mehmet-I kodlarda bir sıkıntı yok. klasörler yanlış olabilir mi?

Akşam detaylıca bakacağım.

**Comment by Mehmet-I** [comment]
> > @Mehmet-I kodlarda bir sıkıntı yok. klasörler yanlış olabilir mi?
> 
> Akşam detaylıca bakacağım. 

Discord adresiniz var mıdır?

**Comment by Mehmet-I** [comment]
> > > @Mehmet-I kodlarda bir sıkıntı yok. klasörler yanlış olabilir mi?
> > 
> > Akşam detaylıca bakacağım. 
> 
> Discord adresiniz var mıdır? 

Telefonumu bootloopa soktum (uygulamayı root explorer ile silince) :) farklı bir rom yükledim dün gece. Bu romda konumlara tekrar bakacağım .

**Comment by Mehmet-I** [comment]
> > > > @Mehmet-I kodlarda bir sıkıntı yok. klasörler yanlış olabilir mi?
> > > 
> > > Akşam detaylıca bakacağım. 
> > 
> > Discord adresiniz var mıdır? 
> 
> Telefonumu bootloopa soktum (uygulamayı root explorer ile silince) :) farklı bir rom yükledim dün gece. Bu romda konumlara tekrar bakacağım .

![Screenshot_2023-05-20-17-02-09-902-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/bf214df7-623e-4004-85f4-2918763fcd33)

![IMG_20230520_170249.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/cce7e66b-3bde-4615-86b8-a2d74a6aacd2)

Uygulama apkları burada eğer konumdan kasıt buysa

**Comment by symbuzzer** [comment]
@Mehmet-I discord yok valla :( Bu attıklarınla kodu bir daha inceleyecem...

**Comment by symbuzzer** [comment]
@Mehmet-I  Mi Browser ve Mi Video için v1.3.1'i yayınladım. Kontrol edebilir misin?

**Comment by symbuzzer** [comment]
@Mehmet-I  Bu arada Game Center hala sıkıntılı mı? sıkıntılıysa onun da net resmini atabilir misin?

**Comment by Mehmet-I** [comment]
> @Mehmet-I  Mi Browser ve Mi Video için v1.3.1'i yayınladım. Kontrol edebilir misin?

İkisi de çalışıyor. Çok teşekkür ediyorum.

**Comment by symbuzzer** [comment]
> > @Mehmet-I  Mi Browser ve Mi Video için v1.3.1'i yayınladım. Kontrol edebilir misin?
> 
> İkisi de çalışıyor. Çok teşekkür ediyorum.

Ben teşekkür ederim :) Game Center?

**Comment by Mehmet-I** [comment]
> @Mehmet-I  Bu arada Game Center hala sıkıntılı mı? sıkıntılıysa onun da net resmini atabilir misin?

Eu rom kurdum bunda öyle bir app göremedim :) ama başka appler atabilirim kurcaladıktan sonra önceki eeaydı. Bu xiaomi.eu

**Comment by Mehmet-I** [comment]
> > @Mehmet-I  Bu arada Game Center hala sıkıntılı mı? sıkıntılıysa onun da net resmini atabilir misin?
> 
> Eu rom kurdum bunda öyle bir app göremedim :) ama başka appler atabilirim kurcaladıktan sonra önceki eeaydı. Bu xiaomi.eu

Stage one üzerinden bir dosyayı çıkarmam mümkün sanırım değil mi? Pc başına oturamadığım için 2 gündür bakamıyorum normalde didik didik ederdim :) Drive yedeklemesi için Google one kullanabiliyorum mesela bu uygulamayı modüle rağmen kullanabilir miyim? Bu roma henüz stage 1 kurmadım. 

Stage 1 kuruyorum google one olmasın zaten :) Hiç gerek yok teşekkür ediyorum.

**Comment by Mehmet-I** [comment]
![Screenshot_2023-05-20-21-53-36-340-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/f0444b85-673e-478f-ba7e-9a1dbf521bad)

![Screenshot_2023-05-20-21-32-53-590-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/eff82961-0ab9-4942-85f4-893b067da755)

![Screenshot_2023-05-20-21-49-29-727_com.miui.securitycenter.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/ab5e7c7f-e7e8-4e13-81d2-12b63c8b63bd)

**Comment by symbuzzer** [comment]
@Mehmet-I  Google One'ı Play Store'dan indir kur. Olmuyor mu?

Mi Mover gerekli bir uygulama, kurulum ekranı çöküyor yoksa. 
Mi Share de gerekli yine hatırlamıyorum nerede ama.

**Comment by Mehmet-I** [comment]
Yeni romda mi müzik modülle gitmemiş maalesef. Bunu buldum. ![Screenshot_2023-05-20-22-31-03-101-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/d6937dbc-95a4-469d-b970-bd9873c9c56c)

**Comment by symbuzzer** [comment]
@Mehmet-I resimleri göremiyorum, düzeltebilir misin?

**Comment by symbuzzer** [comment]
@Mehmet-I Müzik için v1.3.2 çıktı deneyebilir misin?

**Comment by Mehmet-I** [comment]
> @Mehmet-I resimleri göremiyorum, düzeltebilir misin?

Mi Mover ve Mi Share resimleriydi. Yanıtlarken birbirine girdi ben de editle müziği ekledim. Deniyorum şimdi 1.3.2'yi

**Comment by Mehmet-I** [comment]
Çalıştı gayet güzel. Elinize sağlık.

**Comment by symbuzzer** [comment]
Kapatıyorum o halde bu issue'yi? Yeni istekler için yeni issue açabilirsin istersen

**Comment by Mehmet-I** [comment]
Olur tabii.  32 Mesajlı issue mi olur :)
