### ISSUE TITLE
Wps-Lite

### ISSUE THREAD

**Issue by Mehmet-I** [symbuzzer/MIUI-Debloater-Magisk-Modules#3]
Merhaba Ali Bey,

WPS-Lite için de bir modül hazırlayabilir misiniz?

İyi çalışmalar.

![IMG_20230521_005342.jpg](https://github.com/symbuzzer/Poco-Debloater-Magisk-Modules/assets/63732211/145fa54e-d441-4b6b-b283-9415c6d41dce)

**Comment by symbuzzer** [comment]
Tabi yarın hazırlayayım

**Comment by Mehmet-I** [comment]
> Tabi yarın hazırlayayım

Sabahtan beri adaway çalışmıyor :) Çıldıracağım ne olmuş olabilir ki ilk defa başıma geldi. Yıllardır bu programı kullanıyorum her taraf reklam ya. 10 kere sildim yükledim tekrar root izni verdim. Sistemsiz host açtım.

Edit: Rootu kaldırıp tekrar kurdum modülleri tekrar yükledim çalıştı çok şükür.  Oled2lcd önerir misiniz bir yerlerde ekran rengine kalıcı olarak hasar verdiğini okumuştum bu tarz uygulamaların ama hatırlayamıyorum tam. Bunları sorabileceğim bir alan var mı burayı meşgul etmek yerine orayı kullanayım?

**Comment by symbuzzer** [comment]
@Mehmet-I  WPS Lite'ı henüz eklemedim ama daha kolay derlemek adına modülleri mimarisini ve daha genele hitap etsin diye modülün adını değiştirdim. Senden ricam; bütün Poco Debloater Magisk Modullerini kaldırıp şuradakileri yeniden kurman:

https://github.com/symbuzzer/MIUI-Debloater-Magisk-Modules

Çalışıp çalışmayanları raporlarsan sevinirim, teşekkürler

**Comment by Mehmet-I** [comment]
@symbuzzer

Dosya yöneticisi - çalıştı
İndirilenler - çalıştı 
Müzik - çalıştı
Video - çalıştı
Browser - çalıştı
Game center ve sharemi bende yok onları test edemedim. 
Scanner - çalışmadı.

Stage 1'deki uygulamaların çoğu bende yok bazı servislerin gittiğini gördüm ama sim aktifleştirme gibi.

**Comment by symbuzzer** [comment]
@Mehmet-I teşekkür ederim. Scanner için yardımcı olabilir misin? Sendeki dosyasını atabilir misin?

**Comment by Mehmet-I** [comment]
@symbuzzer


![Screenshot_2023-05-21-13-33-20-715-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/MIUI-Debloater-Magisk-Modules/assets/63732211/48894e32-cfa8-46d3-9ae6-bf946ce3aaad)

**Comment by Mehmet-I** [comment]
@symbuzzer bunu da göndereyim elim değmişken

![Screenshot_2023-05-21-13-34-44-609-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/MIUI-Debloater-Magisk-Modules/assets/63732211/511073b1-5cea-4fa5-b76d-655ca1b9f9ca)

**Comment by Mehmet-I** [comment]
@symbuzzer modülü silmeme rağmen Dosya Yöneticisi gelmedi :) Nasıl geri getiririm?

**Comment by symbuzzer** [comment]
@Mehmet-I  öncelikle mi scanner'ı güncelledim. sorunun çözülüp çzülmediğin, kontrol edebilir misin?
Weather ve Wps Lite'ı da ekledim. Onları da kontrol edersen sevinirim.
Modülü kaldırdıktan sonra gelmesi lazım. Cihazı yeniden başlatmayı dene.

**Comment by Mehmet-I** [comment]
@symbuzzer dosya yöneticisi gelmedi. Sildim tekrar kurdum tekrar dosyaları silerek kaldırdım her seferinde yeniden başlattım ama gelmiyor maalesef.

**Comment by symbuzzer** [comment]
> @symbuzzer dosya yöneticisi gelmedi. Sildim tekrar kurdum tekrar dosyaları silerek kaldırdım her seferinde yeniden başlattım ama gelmiyor maalesef. 

Benim modülümle ilgili olmayabilir. Magiskin çalışma prensibi aynı

**Comment by Mehmet-I** [comment]
> @symbuzzer dosya yöneticisi gelmedi. Sildim tekrar kurdum tekrar dosyaları silerek kaldırdım her seferinde yeniden başlattım ama gelmiyor maalesef. 

Play storedan yükledim bunu romdan çıkarıp yüklemeye çalışacağım ama nasıl olur bilmiyorum. Bu arada dosyalar diye ayrı bir app kalıyor modülden sonra da.

![Screenshot_2023-05-21-14-19-14-862-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/MIUI-Debloater-Magisk-Modules/assets/63732211/9a38f6d0-e5fb-48d6-9dbc-d52d40b94158)

**Comment by symbuzzer** [comment]
> > @symbuzzer dosya yöneticisi gelmedi. Sildim tekrar kurdum tekrar dosyaları silerek kaldırdım her seferinde yeniden başlattım ama gelmiyor maalesef. 
> 
> Play storedan yükledim bunu romdan çıkarıp yüklemeye çalışacağım ama nasıl olur bilmiyorum. Bu arada dosyalar diye ayrı bir app kalıyor modülden sonra da.
> 
> ![Screenshot_2023-05-21-14-19-14-862-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/MIUI-Debloater-Magisk-Modules/assets/63732211/9a38f6d0-e5fb-48d6-9dbc-d52d40b94158)
> 
> 

Benim hiç bir modülüm bu dosyaya ellemiyor

**Comment by Mehmet-I** [comment]
@symbuzzer

WPS-Lite çalıştı
Weather çalışmadı.

**Comment by symbuzzer** [comment]
Weather'ın varsa güncellemesini kaldırabilir misin?

**Comment by Mehmet-I** [comment]
> > > @symbuzzer dosya yöneticisi gelmedi. Sildim tekrar kurdum tekrar dosyaları silerek kaldırdım her seferinde yeniden başlattım ama gelmiyor maalesef. 
> > 
> > Play storedan yükledim bunu romdan çıkarıp yüklemeye çalışacağım ama nasıl olur bilmiyorum. Bu arada dosyalar diye ayrı bir app kalıyor modülden sonra da.
> > 
> > ![Screenshot_2023-05-21-14-19-14-862-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/MIUI-Debloater-Magisk-Modules/assets/63732211/9a38f6d0-e5fb-48d6-9dbc-d52d40b94158)
> > 
> > 
> 
> Benim hiç bir modülüm bu dosyaya ellemiyor

![Screenshot_2023-05-21-14-36-19-049-edit_com.miui.securitycenter.jpg](https://github.com/symbuzzer/MIUI-Debloater-Magisk-Modules/assets/63732211/23b00897-cd6a-43d7-86c2-baaa674afe4b)

Ayrıca böyle bir dosya yöneticisi var ondan bahsediyorum. Modül diğerini kaldırdı. Dosyalar adında ikinci bir app var sistem uygulaması.

**Comment by symbuzzer** [comment]
@Mehmet-I bu kalmak zorunda

**Comment by Mehmet-I** [comment]
@symbuzzer hocam ilginç bir problemim var. Chrome host dosyasını tanımıyor. Reklamlar bana mısın demiyor chromeda. İlk defa böyle bir şeye rastladım. Başka 4 5 tarayıcı denedim hiçbirinde reklam yoktu. Gene konu dışı ama :)

**Comment by symbuzzer** [comment]
> @symbuzzer hocam ilginç bir problemim var. Chrome host dosyasını tanımıyor. Reklamlar bana mısın demiyor chromeda. İlk defa böyle bir şeye rastladım. Başka 4 5 tarayıcı denedim hiçbirinde reklam yoktu. Gene konu dışı ama :) 

Konu dışı olmasın lütfen. Benim Ad modülümü kullanıyorsan oraya yazabilirsin
