### ISSUE TITLE
Weather Hatası

### ISSUE THREAD

**Issue by Mehmet-I** [symbuzzer/MIUI-Debloater-Magisk-Modules#5]
Merhaba Ali Bey,

Tespit ettiğim kadarıyla Weather hava durumunu değil YouTube'u siliyor.

**Comment by symbuzzer** [comment]
Merhaba, sorunları buldum. Çözecem en kısa sürede. Teşekkürler geri bildirim için

**Comment by symbuzzer** [comment]
@Mehmet-I Sorunu yeni versiyonda çözüldü. Eğer çalışmazsa yeniden açabilirsin.

**Comment by Mehmet-I** [comment]
Çalışmadı maalesef. @symbuzzer

**Comment by symbuzzer** [comment]
@symbuzzer  güncellemeyi kaldırdınız mı? bir de dosya yolunu doğru attığınıza emin misin?

**Comment by Mehmet-I** [comment]
@symbuzzer 

Evet güncellemeleri kaldırdım.
Şöyle iki ayrı klasör çıkıyor birisinin baş harfi büyük birisininin küçük.

![Screenshot_2023-05-26-12-55-43-171-edit_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/MIUI-Debloater-Magisk-Modules/assets/63732211/fa7f5cce-d995-4596-b310-5528427a273d)

**Comment by symbuzzer** [comment]
@Mehmet-I  v2.0.3'ü deneyebilir misin?

**Comment by Mehmet-I** [comment]
@symbuzzer evet çalıştı.
